name: Build Kernel Rosemary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex libssl-dev libelf-dev zip unzip make clang gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Get Clang 12
        run: |
          mkdir -p $HOME/clang
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-release/clang-r416183b.tar.gz
          tar -xf clang-r416183b.tar.gz -C $HOME/clang

      - name: Setup SukiSU & Fix Configs
        run: |
          curl -LSs "https://raw.githubusercontent.com/sukisu-ultra/sukisu-ultra/main/kernel/setup.sh" | bash -
          echo -e "\nCONFIG_KSU=y\nCONFIG_OVERLAY_FS=y" >> arch/arm64/configs/rosemary_defconfig
          
          # Matikan config yang bentrok dengan Clang 12
          scripts/config --file arch/arm64/configs/rosemary_defconfig --disable CONFIG_VDSO32
          scripts/config --file arch/arm64/configs/rosemary_defconfig --disable CONFIG_COMPAT_VDSO
          scripts/config --file arch/arm64/configs/rosemary_defconfig --disable CONFIG_CC_STACKPROTECTOR_STRONG
          scripts/config --file arch/arm64/configs/rosemary_defconfig --enable CONFIG_CC_STACKPROTECTOR_NONE
          scripts/config --file arch/arm64/configs/rosemary_defconfig --disable CONFIG_LLVM_POLLY
          scripts/config --file arch/arm64/configs/rosemary_defconfig --disable CONFIG_POLLY_CLANG
          
          # Hapus paksa flag Polly LLVM dari semua file Makefile
          find . -name "Makefile" -exec sed -i 's/-mllvm -polly[^ ]*//g' {} +
          find . -name "Makefile" -exec sed -i 's/-mllvm -polly//g' {} +

      - name: Compile
        run: |
          export PATH="$HOME/clang/bin:$PATH"
          
          make ARCH=arm64 O=out rosemary_defconfig
          make -j$(nproc) ARCH=arm64 O=out \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            KCFLAGS="-Wno-error"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz-dtb-SukiSU
          path: out/arch/arm64/boot/Image.gz-dtb
